version: "3.7"
services:
  frontend:
    build: packages/frontend
    ports:
      - "8080:3000"
    networks:
      - satellites-tracker
  backend:
    build: packages/backend
    ports:
      - "49000:49000"
    networks:
      - satellites-tracker
    environment:
      - NODE_ENV=production
      - PORT=49000
      - API_ENDPOINT=https://api.n2yo.com/rest/v1/satellite
      - API_KEY=<N2YO_API_KEY>

networks:
  satellites-tracker:
    driver: bridge
